apiVersion: apps/v1
kind: Deployment
metadata:
  name: revhire-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: revhire
  template:
    metadata:
      labels:
        app: revhire
    spec:
      containers:
      - name: revhire
        image: krishnak3/finalpro0:latest
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: revhir
spec:
  selector:
    app: revhire
  ports:
  - protocol: TCP # "protocol" should be lowercase
    port: 80
    targetPort: 8000
